import { CommandInventoryItem } from "./types";

/** Inventário estático dos principais comandos/botões do sistema. */
export const COMMAND_INVENTORY: CommandInventoryItem[] = [
  {
    tela: "Login",
    botao: "Entrar",
    funcaoEsperada: "Autenticar por R.E. e abrir seletor de semanas",
    perfilPermitido: "Qualquer RE ativo cadastrado",
    acaoFirestore: "Leitura em usuarios",
    geraLog: "Sim (LOGIN)",
  },
  {
    tela: "App / Header",
    botao: "Sair",
    funcaoEsperada: "Encerrar sessão e voltar ao login",
    perfilPermitido: "Todos logados",
    acaoFirestore: "Nenhuma",
    geraLog: "Sim (LOGOUT)",
  },
  {
    tela: "Seletor de Semanas",
    botao: "Selecionar ano (2026–2028)",
    funcaoEsperada: "Recarregar lista de semanas do ano",
    perfilPermitido: "Todos",
    acaoFirestore: "Leitura status das escalas do ano",
    geraLog: "Não",
  },
  {
    tela: "Seletor de Semanas",
    botao: "Abrir semana",
    funcaoEsperada: "Abrir editor da semana",
    perfilPermitido: "Todos",
    acaoFirestore: "Leitura/criação escalas_semanais e escalas_alteracao",
    geraLog: "Não",
  },
  {
    tela: "Seletor de Semanas",
    botao: "Configurações",
    funcaoEsperada: "Abrir painel administrativo",
    perfilPermitido: "Administrador",
    acaoFirestore: "Leitura de cadastros",
    geraLog: "Não",
  },
  {
    tela: "Seletor de Semanas",
    botao: "Aprovar Semanal / Alteração",
    funcaoEsperada: "Abrir fluxo de aprovação da semana",
    perfilPermitido: "Gestor",
    acaoFirestore: "Resolve token / carrega escala",
    geraLog: "Sim (ABRIR_LINK_APROVACAO)",
  },
  {
    tela: "Escala Semanal",
    botao: "Salvar",
    funcaoEsperada: "Persistir linhas e observações por usuário",
    perfilPermitido: "Admin / Operador (conforme status e semana)",
    acaoFirestore: "setDoc escalas_semanais",
    geraLog: "Sim (SALVAR_ESCALA_SEMANAL) se houver diffs",
  },
  {
    tela: "Escala Semanal",
    botao: "Enviar para Aprovação",
    funcaoEsperada: "Criar solicitação com token e link",
    perfilPermitido: "Administrador",
    acaoFirestore: "setDoc escala + solicitacoes_aprovacao",
    geraLog: "Sim (ENVIAR_ESCALA_SEMANAL)",
  },
  {
    tela: "Escala Semanal",
    botao: "Cancelar solicitação",
    funcaoEsperada: "Voltar escala para edição",
    perfilPermitido: "Administrador (aguardando_aprovacao)",
    acaoFirestore: "setDoc escala + finalize solicitação",
    geraLog: "Sim (CANCELAR)",
  },
  {
    tela: "Escala Semanal",
    botao: "Link / Copiar Link",
    funcaoEsperada: "Exibir/copiar link de aprovação",
    perfilPermitido: "Administrador",
    acaoFirestore: "Leitura token",
    geraLog: "Não",
  },
  {
    tela: "Escala Semanal",
    botao: "Obs. (por militar)",
    funcaoEsperada: "Abrir painel de observação individual",
    perfilPermitido: "Quem pode editar",
    acaoFirestore: "Persistido no Salvar (campo observacao da linha)",
    geraLog: "Sim (via SALVAR se alterado)",
  },
  {
    tela: "Escala Semanal",
    botao: "Alterar (copiar para Escala Alteração)",
    funcaoEsperada: "Copiar militar para painel de alteração",
    perfilPermitido: "Quem pode editar Escala Alteração",
    acaoFirestore: "Somente local até Salvar Alteração",
    geraLog: "Não até salvar",
  },
  {
    tela: "Escala Semanal",
    botao: "Dados da semana anterior",
    funcaoEsperada: "Carregar dados reais da Escala Semanal anterior (confirmação; sem gravar)",
    perfilPermitido: "Quem pode editar a Escala Semanal",
    acaoFirestore: "Somente leitura em escalas_semanais/{semanaAnterior}; gravação só após Salvar",
    geraLog: "Sim (LOAD_PREVIOUS_WEEK_DATA)",
  },
  {
    tela: "Escala Semanal",
    botao: "Limpar escala",
    funcaoEsperada:
      "Restaurar campos editáveis ao estado inicial em memória (mantém colaboradores; sem gravar)",
    perfilPermitido: "Quem pode editar a Escala Semanal (bloqueado se aprovada)",
    acaoFirestore: "Nenhuma até Salvar; não altera Escala Alteração nem outras semanas",
    geraLog: "Sim (CLEAR_WEEKLY_SCHEDULE)",
  },
  {
    tela: "Escala Alteração",
    botao: "Limpar escala",
    funcaoEsperada: "Não aplicável nesta etapa (sem botão)",
    perfilPermitido: "—",
    acaoFirestore: "Nenhuma",
    geraLog: "Não",
  },
  {
    tela: "Escala Alteração",
    botao: "Dados da semana anterior",
    funcaoEsperada: "Não aplicável nesta etapa (sem botão)",
    perfilPermitido: "—",
    acaoFirestore: "Nenhuma",
    geraLog: "Não",
  },
  {
    tela: "Escala Alteração",
    botao: "Salvar / Enviar / Cancelar / Link",
    funcaoEsperada: "Ciclo independente da Escala Semanal",
    perfilPermitido: "Mesmas regras por perfil",
    acaoFirestore: "escalas_alteracao + solicitacoes_aprovacao",
    geraLog: "Sim (tipos *_ALTERACAO)",
  },
  {
    tela: "Escala / Exportar",
    botao: "Exportar PDF / Excel",
    funcaoEsperada: "Gerar arquivo da semana selecionada",
    perfilPermitido: "Todos logados",
    acaoFirestore: "Nenhuma (local)",
    geraLog: "Sim (EXPORTAR)",
  },
  {
    tela: "Aprovação",
    botao: "Aprovar",
    funcaoEsperada: "Aprovar escala e finalizar solicitação",
    perfilPermitido: "Gestor",
    acaoFirestore: "setDoc escala + finalize solicitação",
    geraLog: "Sim (APROVAR_*)",
  },
  {
    tela: "Aprovação",
    botao: "Solicitar Revisão",
    funcaoEsperada: "Devolver escala com motivo",
    perfilPermitido: "Gestor",
    acaoFirestore: "setDoc escala + finalize solicitação",
    geraLog: "Sim (SOLICITAR_REVISAO_*)",
  },
  {
    tela: "Configurações",
    botao: "Legendas (CRUD expandido)",
    funcaoEsperada:
      "Cadastro com sigla/nome/descrição + representações e regras opcionais (preparação Consolidada)",
    perfilPermitido: "Administrador",
    acaoFirestore: "writeBatch legendas (campos novos opcionais; legados preservados)",
    geraLog: "Sim (ALTERAR_CONFIGURACAO / Legendas)",
  },
  {
    tela: "Configurações",
    botao: "Salvar Configurações",
    funcaoEsperada: "Persistir CRUDs (colaboradores, permissão, postos, seções, legendas, gerais)",
    perfilPermitido: "Administrador",
    acaoFirestore: "writeBatch nas coleções",
    geraLog: "Sim (ALTERAR_CONFIGURACAO)",
  },
  {
    tela: "Configurações",
    botao: "Central de Testes",
    funcaoEsperada: "Executar suítes de verificação funcional",
    perfilPermitido: "Administrador",
    acaoFirestore: "Somente docs test_* sob confirmação",
    geraLog: "Opcional (detalhes SISTEMA)",
  },
  {
    tela: "Seletor de Semanas",
    botao: "CONTROLE DE FREQUÊNCIA",
    funcaoEsperada: "Abrir seletor de meses do ano selecionado",
    perfilPermitido: "Todos",
    acaoFirestore: "Leitura status controle_frequencia do ano",
    geraLog: "Não",
  },
  {
    tela: "Controle de Frequência",
    botao: "Selecionar mês / seção",
    funcaoEsperada: "Abrir editor mensal por seção",
    perfilPermitido: "Todos",
    acaoFirestore: "Leitura/criação controle_frequencia",
    geraLog: "Não",
  },
  {
    tela: "Controle de Frequência",
    botao: "Sincronizar escalas",
    funcaoEsperada:
      "Recarregar células a partir de Alteração > Semanal; preserva edição manual",
    perfilPermitido: "Admin / Operador (mês editável)",
    acaoFirestore: "setDoc controle_frequencia + leitura escalas",
    geraLog: "Sim (SYNC_CONTROLE_FREQUENCIA)",
  },
  {
    tela: "Controle de Frequência",
    botao: "Salvar",
    funcaoEsperada: "Persistir tabela, totais e observações",
    perfilPermitido: "Admin / Operador (conforme status e mês)",
    acaoFirestore: "setDoc controle_frequencia",
    geraLog: "Sim (SALVAR_CONTROLE_FREQUENCIA)",
  },
  {
    tela: "Controle de Frequência",
    botao: "Enviar / Aprovar / Imprimir",
    funcaoEsperada:
      "Fluxo de aprovação reutilizado + impressão A4 paisagem",
    perfilPermitido: "Admin envia; Gestor aprova; todos imprimem",
    acaoFirestore: "controle_frequencia + solicitacoes_aprovacao",
    geraLog: "Sim (ENVIAR_/APROVAR_CONTROLE_FREQUENCIA)",
  },
];
